# -*- coding: utf-8 -*-
"""Modelo_2_predictivo_clasificacion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d5FcNW4CiQtvquZAudk2AVrqpcvGoxDt

# Modelo 9 — Clasificacion: Regresion Logistica (`Prebook`)

**Objetivo:** predecir si la carga fue prebooked (`Prebook`: Prebooked vs Not Prebooked).

**Modelo (eleccion aleatoria):** `LogisticRegression`.

**Fuente:** `01_DataClean/cleaned_data_shipment.csv`

**Metricas:** Accuracy, Precision, Recall, F1, curva ROC y validacion cruzada estratificada.

## 1. Importacion de librerias
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn import metrics

"""## 2. Carga y verificacion de la base de datos

"""

BASE_DIR = Path('.').resolve()
PATH = '/content/drive/MyDrive/5. UPB Maestría/SEMESTRE 1/02_Mineria_de_datos/PROYECTO/01_DataClean/cleaned_data_shipment.csv'



df = pd.read_csv(PATH)
print('Shape:', df.shape)
df.head()

"""## 3. Limpieza y binarizacion de la target `Prebook`

"""

df['Status'] = df['Status'].astype(str).str.strip().str.upper()
df['FallOff'] = df['FallOff'].astype(str).str.strip().str.upper()
df['FallOff'] = df['FallOff'].map({'TRUE': 1, 'FALSE': 0})
print('Nulos totales:', df.isnull().sum().sum())
print('\nPrebook crudo:')
print(df['Prebook'].value_counts())

# Binarizar: Prebooked=1, Not Prebooked=0
df['Prebook_bin'] = (
    df['Prebook'].astype(str)
    .str.replace("'", '', regex=False)
    .str.strip()
    .str.lower()
    .map({'prebooked': 1, 'not prebooked': 0})
)
print('Prebook_bin:', df['Prebook_bin'].value_counts(dropna=False).to_dict())
print(df['Prebook_bin'].value_counts(normalize=True).round(4))
assert df['Prebook_bin'].notna().all(), 'Quedaron valores no mapeados en Prebook'

"""## 4. Definicion de X e y

Se elimina `Prebook` original (leakage) y se usa `Prebook_bin` como y.

"""

y = df['Prebook_bin'].astype(int)
x = df.drop(columns=['Prebook', 'Prebook_bin', 'Origin_Zip', 'Destination_Zip'])
print('Predictoras:', list(x.columns))
print('Clases:', y.value_counts().to_dict())
x.head()

"""## 5. Categoricas a dummies

"""

x = pd.get_dummies(
    x,
    columns=['Mode', 'Equipment', 'General_Pricing_Category'],
    drop_first=False,
    dtype=int
)
x = pd.get_dummies(
    x,
    columns=['Roll_Over', 'Stop_Type', 'Status'],
    drop_first=True,
    dtype=int
)
print('Shape tras dummies:', x.shape)
x.head()

"""## 6. Estandarizacion de numericas (importante para regresion logistica)

"""

numeric_cols = ['Miles', 'CarrierPay', 'CustomerPay', 'Total_Drops']
scaler = StandardScaler()
x[numeric_cols] = scaler.fit_transform(x[numeric_cols])
x[numeric_cols].describe().round(4)

"""## 7. Division train/test 70/30 estratificada

"""

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, stratify=y, random_state=42
)
print('Train:', X_train.shape, 'Test:', X_test.shape)
print(y_train.value_counts(normalize=True).round(4))

"""## 8. Entrenamiento Logistic Regression

"""

model_lr = LogisticRegression(
    max_iter=500,
    class_weight='balanced',
    solver='lbfgs',
    random_state=42
)
model_lr.fit(X_train, y_train)
print('Modelo entrenado:', model_lr)

"""## 9. Evaluacion hold-out + ROC

"""

y_pred = model_lr.predict(X_test)
y_proba = model_lr.predict_proba(X_test)[:, 1]

print('Accuracy :', metrics.accuracy_score(y_test, y_pred))
print('Precision:', metrics.precision_score(y_test, y_pred, zero_division=0))
print('Recall   :', metrics.recall_score(y_test, y_pred, zero_division=0))
print('F1       :', metrics.f1_score(y_test, y_pred, zero_division=0))
print('ROC-AUC  :', metrics.roc_auc_score(y_test, y_proba))
print('\nReporte:')
print(metrics.classification_report(y_test, y_pred, zero_division=0))

cm = metrics.confusion_matrix(y_test, y_pred)
metrics.ConfusionMatrixDisplay(confusion_matrix=cm).plot()
plt.title('Matriz de confusion — Logistic Regression (Prebook)')
plt.show()

metrics.RocCurveDisplay.from_predictions(y_test, y_proba)
plt.title('Curva ROC — Logistic Regression (Prebook)')
plt.show()

"""## 10. Coeficientes (interpretacion de influencia)

"""

coef = pd.Series(model_lr.coef_.ravel(), index=X_train.columns).sort_values(key=abs, ascending=False)
coef.head(15).iloc[::-1].plot(kind='barh', figsize=(8, 5), color='teal')
plt.title('Top |coeficientes| — Logistic Regression (Prebook)')
plt.tight_layout()
plt.show()
coef.head(15)

"""## 11. Validacion cruzada estratificada (10 folds)

"""

cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
scoring = ('accuracy', 'precision', 'recall', 'f1', 'roc_auc')
model_cv = LogisticRegression(
    max_iter=500, class_weight='balanced', solver='lbfgs', random_state=42
)
scores = cross_validate(
    model_cv, x, y, cv=cv, scoring=scoring, return_train_score=True, n_jobs=-1
)
scores_df = pd.DataFrame(scores)
scores_df

"""## 12. Resumen CV

"""

resumen = pd.DataFrame({
    'mean_test': [
        scores_df['test_accuracy'].mean(), scores_df['test_precision'].mean(),
        scores_df['test_recall'].mean(), scores_df['test_f1'].mean(),
        scores_df['test_roc_auc'].mean(),
    ],
    'std_test': [
        scores_df['test_accuracy'].std(), scores_df['test_precision'].std(),
        scores_df['test_recall'].std(), scores_df['test_f1'].std(),
        scores_df['test_roc_auc'].std(),
    ],
    'mean_train': [
        scores_df['train_accuracy'].mean(), scores_df['train_precision'].mean(),
        scores_df['train_recall'].mean(), scores_df['train_f1'].mean(),
        scores_df['train_roc_auc'].mean(),
    ],
}, index=['Accuracy', 'Precision', 'Recall', 'F1', 'ROC-AUC'])
print('Resumen CV 10-fold — Logistic Regression / Prebook')
resumen.round(4)