# -*- coding: utf-8 -*-
"""Modelo_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wdfmFVK2LI19vdKFJaUKSyaiCg7iRUZF
"""

import pandas as pd

#Ruta local del archivo y opción para generar solamente el modelo
import argparse
from pathlib import Path

parser = argparse.ArgumentParser(description='Entrenar y guardar el Modelo 1.')
parser.add_argument('archivo', nargs='?', default=str(Path(__file__).with_name('cleaned_data_shipment.csv')))
parser.add_argument('--solo-exportar', action='store_true', help='Guardar el .pkl sin ejecutar los gráficos y evaluaciones posteriores.')
args = parser.parse_args()

PATH = args.archivo

df = pd.read_csv(PATH, dtype={'Origin_Zip': str})

df.info()

"""Quitar las variables de correlación"""



df.Status = df.Status.apply(lambda x: x.strip())
df.Status = df.Status.apply(lambda x: x.upper())

df.FallOff = df.FallOff.apply(lambda x: x.strip() if isinstance(x, str) else x)

df.Status.value_counts().plot(kind='bar')

pd.DataFrame(df.info())

df.Mode = df.Mode.astype('category')
df.Equipment = df.Equipment.astype('category')
df.Roll_Over = df.Roll_Over.astype('category')
df.Prebook = df.Prebook.astype('category')
df.General_Pricing_Category = df.General_Pricing_Category.astype('category')
df.Stop_Type = df.Stop_Type.astype('category')
df.Origin_Zip = df.Origin_Zip.str.strip(" '\"").str.upper().astype('category')
df.Status = df.Status.astype('category')
df.FallOff = df.FallOff.astype('category')

df.info()

df.FallOff                   .value_counts().plot(kind='bar')

"""Vamos a predecir status"""

x = df.drop('Status', axis=1)
y = df.Status

x

#Guardamos las variables originales y sus opciones para la interfaz gráfica
entradas = {}
for variable in x.columns:
    if isinstance(x[variable].dtype, pd.CategoricalDtype):
        entradas[variable] = x[variable].cat.categories.tolist()
    elif pd.api.types.is_integer_dtype(x[variable]):
        entradas[variable] = int(x[variable].median())
    else:
        entradas[variable] = float(x[variable].median())

#Nombres de los estados, en el mismo orden que utiliza get_dummies
estados = df.Status.cat.categories.tolist()

"""Dummies"""

x = pd.get_dummies(x, columns=['Mode', 'Equipment', 'General_Pricing_Category', 'Origin_Zip'], drop_first=False, dtype=int)
x = pd.get_dummies(x, columns=['Roll_Over','Prebook','Stop_Type', 'FallOff'], drop_first=True, dtype=int)

x.head()

y = pd.get_dummies(y, columns=['Status'], drop_first=True, dtype=int)
y.head()

"""División 70/30"""

#División 70-30
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.3, stratify=y) #Muestreo estratificado
Y_train.value_counts().plot(kind='bar')

#Creación del modelo con el conjunto de entrenamiento
from sklearn.tree import DecisionTreeClassifier #DecisionTreeRegressor

modelTree = DecisionTreeClassifier(criterion='gini', min_samples_leaf=50, max_depth=10) #gini, entropy
modelTree.fit(X_train, Y_train) #70% train

#Guardamos el modelo entrenado antes de volver a crear modelTree en Cross validation
import pickle
variables = X_train.columns.tolist()
error = 1 - modelTree.score(X_test, Y_test)
filename = Path(__file__).with_name('modelo_1.pkl')
with open(filename, 'wb') as archivo:
    pickle.dump((modelTree, variables, entradas, estados, error), archivo)
print(f'Modelo guardado en: {filename}')

if args.solo_exportar:
    raise SystemExit(0)

import matplotlib.pyplot as plt
from sklearn.tree import plot_tree
plt.figure(figsize=(30,20)) #Tamaño de la imagen
plot_tree(modelTree, feature_names=X_train.columns.values, rounded=True,  fontsize=8, filled=True)
plt.show()

#Evaluación 30% (X_test)
from sklearn import metrics

Y_pred = modelTree.predict(X_test) #30% Test
print(Y_pred)

#Exactitud: Correctos/Total
exactitud=metrics.accuracy_score(y_true=Y_test, y_pred=Y_pred)
print(exactitud)

#Matriz de confusion
from sklearn import metrics

cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
cm

#Plot de la matriz de confusion
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,)
disp.plot()

#Precision, Recall, f1, exactitud

print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred))

metrics.RocCurveDisplay.from_estimator(modelTree,X_test, Y_test)

df.to_csv('cleaned_data_VF.csv')

#En local el CSV queda guardado en la carpeta desde la que se ejecuta el script

"""Cross validation"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Validación Cruzada
from sklearn.model_selection import cross_validate, StratifiedKFold

#Dataframe para comparar los modelos
comparacion_CV=pd.DataFrame()
scoring=('f1_macro', 'accuracy','precision_macro', 'recall_macro')
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42) #Muestreo estratificado

#Tree
from sklearn import tree
modelTree = tree.DecisionTreeClassifier(criterion='gini', min_samples_leaf=50, max_depth=10)

scores = cross_validate(modelTree, x, y, cv=cv, scoring=scoring, return_train_score=True, return_estimator=False)
scores=pd.DataFrame(scores) #Se almacenan los resultados en un dataframe
scores
